const myos=require('os')
console.log("Architechure: "+ myos.arch())
console.log("Platform: "+myos.platform())
console.log("Total memory: "+myos.totalmem())
console.log("Free memory: "+myos.freemem())
console.log("Home directory: "+myos.homedir())
console.log("Hostname: "+myos.hostname())
console.log("Release: "+myos.release())
console.log("Type: "+myos.type())
console.log("Order in which bytes are stored: "+myos.endianness())
console.log("Temp Directory: "+myos.tmpdir())