const mypath=require('path')
console.log(mypath.basename(__filename))
console.log(mypath.dirname(__filename))
console.log(mypath.delimiter)
console.log(mypath.extname(__filename))
console.log(mypath.parse(__filename))
console.log(mypath.isAbsolute(__filename))
console.log(mypath.isAbsolute('myfile.txt'))
console.log(mypath.relative('C:\Users',__filename))