var mypath = require('os')
console.log("Architecture" + mypath.arch())
console.log("Total memory" + mypath.totalmem())
console.log("Free memory" + mypath.freemem())
console.log("Temp directory" + mypath.tmpdir())
console.log("Platform" + mypath.platform())
console.log("Release" + mypath.release())
console.log("Endianess" + mypath.endianness())
console.log("Type of os" + mypath.type())
console.log("Hostname" + mypath.hostname())
